### ISSUE TITLE
Error when running bros

### ISSUE THREAD

**Issue by doxsec** [gabemarshall/Brosec#18]
here is the error i get when i run brosec

util.js:965
    throw new TypeError('The super constructor to "inherits" must not ' +
    ^

TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.exports.inherits (util.js:965:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/Brosec/node_modules/ftpd/lib/ftpd.js:67:6)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/Brosec/modules/webserver/simpleFtp.js:1:74)

**Comment by gabemarshall** [comment]
Thanks for trying it out doxec, sorry you had trouble. Can you let me know what version of nodejs you have installed so I can try to replicate the issue? (node -v)

**Comment by doxsec** [comment]
here u go            v7.0.0

**Comment by gabemarshall** [comment]
Thanks!

**Comment by doxsec** [comment]
please let me know how it goes :) cant wait to have brosec running :D

**Comment by gabemarshall** [comment]
I'm getting the same when running it with v7.0.0

Looks like an issue with the ftp library I'm using.. I'll try to get it fixed asap. In the meantime you, installing an older version of nodejs would get around the error.. Sorry about that =/

**Comment by gabemarshall** [comment]
Just pushed an update that should fix the problem temporarily. Either do a git pull && npm install or reinstall from scratch. Let me know if you have any other issues!

**Comment by wayofthefuture** [comment]
Not working over here...

**Comment by wayofthefuture** [comment]
Solved by installing from GitHub:

> npm i https://github.com/sstur/nodeftpd.git --save
